### ISSUE TITLE
Importing private keys

### ISSUE THREAD

**Issue by iridian-ks** [pulumi/pulumi-tls#48]
Hello,

I was wondering how we're supposed to go about importing a PrivateKey?

I've tried a few things like bringing in my old tfstate and using it's ID for the private_key, but that doesn't seem to work.

Any tips would be helpful.

Thanks!

**Comment by leezen** [comment]
Since it's a resource in TF state, you could try using https://github.com/pulumi/pulumi-terraform 
to use the existing key. However, I don't think there's an easy way to 'adopt' the existing key into Pulumi state. Since it is unencrypted in the TF state, you could technically copy that and manually create the correct JSON in Pulumi state if you really wanted to keep the key the same.

**Comment by iridian-ks** [comment]
OK, I do want to keep the key the same. I can manually import the key. Would There be a way for Pulumi to encrypt the state after I do that? Or is that left unencrypted in Pulumi as well?

**Comment by leezen** [comment]
Yes, after bringing in the resource, you should be able to set `{ additionalSecretOutputs: ["privateKeyPem"] }` on the key.
